wandb_version: 1

device:
  value: NVIDIA L40S
freeze:
  value: 'true'
lr:
  value: 0.0006751163909277016
mode:
  value: full
model:
  value: resnet
num_epochs:
  value: 234
optimizer:
  value: adam
weight_decay:
  value: 0.08610646104665887
