wandb_version: 1

device:
  value: NVIDIA L40S
freeze:
  value: 'false'
lr:
  value: 0.0005286074369483773
mode:
  value: full
model:
  value: resnet
num_epochs:
  value: 139
optimizer:
  value: adam
weight_decay:
  value: 0.1163793798086208
