wandb_version: 1

device:
  value: NVIDIA L40S
freeze:
  value: 'false'
lr:
  value: 0.0004380856102981646
mode:
  value: full
model:
  value: resnet
num_epochs:
  value: 179
optimizer:
  value: adam
weight_decay:
  value: 0.0591907129162015
