wandb_version: 1

device:
  value: NVIDIA L40S
freeze:
  value: 'true'
lr:
  value: 0.0008500230015457788
mode:
  value: full
model:
  value: resnet
num_epochs:
  value: 185
optimizer:
  value: adam
weight_decay:
  value: 0.09246474659008665
