wandb_version: 1

device:
  value: NVIDIA L40S
freeze:
  value: 'false'
lr:
  value: 0.0009235384797037012
mode:
  value: full
model:
  value: resnet
num_epochs:
  value: 205
optimizer:
  value: adam
weight_decay:
  value: 0.15137713170834216
