wandb_version: 1

device:
  value: NVIDIA L40S
freeze:
  value: 'false'
lr:
  value: 0.0005961086583929555
mode:
  value: full
model:
  value: resnet
num_epochs:
  value: 185
optimizer:
  value: adam
weight_decay:
  value: 0.045450293100613
