wandb_version: 1

device:
  value: NVIDIA L40S
freeze:
  value: 'true'
lr:
  value: 0.0007326002769664631
mode:
  value: full
model:
  value: resnet
num_epochs:
  value: 125
optimizer:
  value: adam
weight_decay:
  value: 0.07719989227005225
