wandb_version: 1

device:
  value: NVIDIA L40S
freeze:
  value: 'true'
lr:
  value: 0.0006338971908507521
mode:
  value: full
model:
  value: resnet
num_epochs:
  value: 207
optimizer:
  value: adam
weight_decay:
  value: 0.1451387461881265
