wandb_version: 1

device:
  value: NVIDIA L40S
freeze:
  value: 'false'
lr:
  value: 0.0005959122210186614
mode:
  value: full
model:
  value: resnet
num_epochs:
  value: 133
optimizer:
  value: adam
weight_decay:
  value: 0.16037027118859773
