wandb_version: 1

device:
  value: NVIDIA L40S
freeze:
  value: 'true'
lr:
  value: 0.0007345283040760008
mode:
  value: full
model:
  value: resnet
num_epochs:
  value: 173
optimizer:
  value: adam
weight_decay:
  value: 0.04112577411856802
