wandb_version: 1

device:
  value: NVIDIA L40S
freeze:
  value: 'false'
lr:
  value: 0.000901137560704664
mode:
  value: full
model:
  value: resnet
num_epochs:
  value: 285
optimizer:
  value: adam
weight_decay:
  value: 0.06939320982315446
