wandb_version: 1

device:
  value: NVIDIA L40S
freeze:
  value: 'true'
lr:
  value: 0.0009666226899502364
mode:
  value: full
model:
  value: resnet
num_epochs:
  value: 287
optimizer:
  value: adam
weight_decay:
  value: 0.15948033770086853
