wandb_version: 1

device:
  value: NVIDIA L40S
freeze:
  value: 'false'
lr:
  value: 0.0006706371089996668
mode:
  value: full
model:
  value: resnet
num_epochs:
  value: 213
optimizer:
  value: adam
weight_decay:
  value: 0.14037667247818922
