wandb_version: 1

device:
  value: NVIDIA L40S
freeze:
  value: 'false'
lr:
  value: 0.0007001759985147352
mode:
  value: full
model:
  value: resnet
num_epochs:
  value: 90
optimizer:
  value: adam
weight_decay:
  value: 0.014227249240414203
