wandb_version: 1

device:
  value: NVIDIA L40S
freeze:
  value: 'false'
lr:
  value: 0.00033144719900331677
mode:
  value: full
model:
  value: resnet
num_epochs:
  value: 302
optimizer:
  value: adam
weight_decay:
  value: 0.13432104713387824
