wandb_version: 1

device:
  value: NVIDIA L40S
freeze:
  value: 'true'
lr:
  value: 0.000713505706787297
mode:
  value: full
model:
  value: resnet
num_epochs:
  value: 232
optimizer:
  value: adam
weight_decay:
  value: 0.18841150193846604
