wandb_version: 1

device:
  value: NVIDIA L40S
freeze:
  value: 'false'
lr:
  value: 0.0009684280744430518
mode:
  value: full
model:
  value: resnet
num_epochs:
  value: 235
optimizer:
  value: adam
weight_decay:
  value: 0.03862991110334886
